// src/core/ShaderBuilder.js

export class ShaderBuilder {
    constructor() {
        this.modeCodes = new Map();
    }

    registerMode(mode) {
        this.modeCodes.set(mode.name, mode.getShaderCode());
    }

    buildVertexShader() {
        return `#version 100
            attribute vec2 a_position;
            varying vec2 v_uv;
            uniform float u_time;
            uniform float u_loopDuration;
            void main() {
                float angle = (u_loopDuration > 0.0) ? (6.28318530718 * u_time / u_loopDuration) : 0.0;
                float breathe = 1.02 + 0.02 * sin(angle);
                gl_Position = vec4(a_position * breathe, 0.0, 1.0);
                v_uv = (a_position + 1.0) / 2.0;
            }`;
    }

    getSharedFunctions() {
        return `
            float hash(vec2 p) {
                return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
            }
            float noise(vec2 p) {
                vec2 i = floor(p);
                vec2 f = fract(p);
                f = f * f * (3.0 - 2.0 * f);
                return mix(mix(hash(i), hash(i + vec2(1.0, 0.0)), f.x),
                           mix(hash(i + vec2(0.0, 1.0)), hash(i + vec2(1.0, 1.0)), f.x), f.y);
            }
            float fbm(vec2 p) {
                float v = 0.0, a = 0.5, f = 1.0;
                for (int i = 0; i < 8; i++) {
                    if (float(i) >= u_complexity) break;
                    v += a * noise(p * f);
                    f *= 2.0;
                    a *= 0.6;
                }
                return v;
            }
        `;
    }

    /**
     * Capitalize the first letter of a mode name to build its render function
     * name, e.g. "psychedelic" -> "renderPsychedelic".
     */
    capitalize(name) {
        return name.charAt(0).toUpperCase() + name.slice(1);
    }

    /**
     * Build the mode dispatch block. Every mode gets the SAME seamless-loop
     * treatment: the pattern is computed at t and at t - loopDuration and
     * linearly cross-faded across the loop duration. Because both samples are
     * generated by the exact same continuous function of time, this
     * guarantees frame(0) === frame(loopDuration), i.e. a seamless loop,
     * regardless of whether the underlying pattern is itself periodic.
     */
    buildModeDispatch(modeList) {
        let block = '';
        modeList.forEach((name, index) => {
            const funcName = `render${this.capitalize(name)}`;
            const keyword = index === 0 ? 'if' : 'else if';
            block += `
            ${keyword} (u_mode == ${index}) {
                if (u_loopDuration > 0.0 && loopDuration > 0.0) {
                    float blend = clamp(t / loopDuration, 0.0, 1.0);
                    vec3 colA = ${funcName}(uv, t);
                    vec3 colB = ${funcName}(uv, t - loopDuration);
                    pattern = mix(colA, colB, blend);
                } else {
                    pattern = ${funcName}(uv, t);
                }
            }`;
        });
        return block;
    }

    buildFragmentShader(modeNames) {
        let modeCode = '';
        const modeList = [];
        modeNames.forEach((name) => {
            const code = this.modeCodes.get(name);
            if (code) {
                modeCode += code;
                modeList.push(name);
            }
        });

        const modeDispatch = this.buildModeDispatch(modeList);

        return `#version 100
        precision highp float;
        varying vec2 v_uv;
        
        uniform float u_time, u_loopDuration, u_aspect;
        uniform vec3 u_p0, u_p1, u_p2, u_p3, u_p4, u_p5;
        uniform float u_pCount;
        uniform int u_mode;
        
        uniform float u_distortion, u_complexity, u_speed, u_scale;
        uniform float u_blobCount, u_blobSize, u_blobSpeed, u_blobWobble;
        uniform float u_segments, u_rotationSpeed, u_zoom;
        uniform float u_fluidTurbulence, u_fluidSpeed, u_fluidScale, u_fluidSwirl;
        uniform float u_tunnelRings, u_tunnelSpeed, u_tunnelTwist, u_tunnelGlow;
        uniform float u_morphShapes, u_morphSpeed, u_morphScale, u_morphBlend;
        uniform float u_liquidShine, u_liquidFlow, u_liquidScale, u_liquidRipple;
        uniform float u_mandelbrotIter, u_mandelbrotZoom, u_mandelbrotJuliaMix, u_mandelbrotSpeed;
        uniform float u_fireIntensity, u_fireSpeed, u_fireTurbulence, u_fireHeight;
        uniform float u_auroraBands, u_auroraSpeed, u_auroraWave, u_auroraGlow;
        uniform float u_particleCount, u_particleSpeed, u_particleSize, u_particleTrail;
        
        ${this.getSharedFunctions()}
        
        ${modeCode}
        
        vec3 mixPalette(float idx) {
            vec3 col;
            if (idx < 1.0) col = mix(u_p0, u_p1, idx);
            else if (idx < 2.0) col = mix(u_p1, u_p2, idx - 1.0);
            else if (idx < 3.0) col = mix(u_p2, u_p3, idx - 2.0);
            else if (idx < 4.0) col = mix(u_p3, u_p4, idx - 3.0);
            else col = mix(u_p4, u_p5, clamp(idx - 4.0, 0.0, 1.0));
            return col;
        }
        
        void main() {
            vec2 uv = v_uv;
            uv.x *= u_aspect;
            float t = u_time * u_speed;
            float loopDuration = u_loopDuration * u_speed;
            
            vec3 pattern = vec3(0.0);
            
            // ========== ALL MODES: GENERIC SEAMLESS-LOOP CROSSFADE ==========
            ${modeDispatch}
            
            float idx = pattern.r * (u_pCount - 1.0);
            vec3 col = mixPalette(idx);
            
            float vig = clamp(1.0 - length(v_uv - 0.5) * 1.2, 0.0, 1.0);
            col *= vig * 0.9 + 0.2;
            gl_FragColor = vec4(col, 1.0);
        }`;
    }

    getUniformLocations(gl, program) {
        return {
            time: gl.getUniformLocation(program, 'u_time'),
            loopDuration: gl.getUniformLocation(program, 'u_loopDuration'),
            aspect: gl.getUniformLocation(program, 'u_aspect'),
            pCount: gl.getUniformLocation(program, 'u_pCount'),
            p0: gl.getUniformLocation(program, 'u_p0'),
            p1: gl.getUniformLocation(program, 'u_p1'),
            p2: gl.getUniformLocation(program, 'u_p2'),
            p3: gl.getUniformLocation(program, 'u_p3'),
            p4: gl.getUniformLocation(program, 'u_p4'),
            p5: gl.getUniformLocation(program, 'u_p5'),
            mode: gl.getUniformLocation(program, 'u_mode'),
            distortion: gl.getUniformLocation(program, 'u_distortion'),
            complexity: gl.getUniformLocation(program, 'u_complexity'),
            speed: gl.getUniformLocation(program, 'u_speed'),
            scale: gl.getUniformLocation(program, 'u_scale'),
            blobCount: gl.getUniformLocation(program, 'u_blobCount'),
            blobSize: gl.getUniformLocation(program, 'u_blobSize'),
            blobSpeed: gl.getUniformLocation(program, 'u_blobSpeed'),
            blobWobble: gl.getUniformLocation(program, 'u_blobWobble'),
            segments: gl.getUniformLocation(program, 'u_segments'),
            rotationSpeed: gl.getUniformLocation(program, 'u_rotationSpeed'),
            zoom: gl.getUniformLocation(program, 'u_zoom'),

            fluidTurbulence: gl.getUniformLocation(program, 'u_fluidTurbulence'),
            fluidSpeed: gl.getUniformLocation(program, 'u_fluidSpeed'),
            fluidScale: gl.getUniformLocation(program, 'u_fluidScale'),
            fluidSwirl: gl.getUniformLocation(program, 'u_fluidSwirl'),

            tunnelRings: gl.getUniformLocation(program, 'u_tunnelRings'),
            tunnelSpeed: gl.getUniformLocation(program, 'u_tunnelSpeed'),
            tunnelTwist: gl.getUniformLocation(program, 'u_tunnelTwist'),
            tunnelGlow: gl.getUniformLocation(program, 'u_tunnelGlow'),

            morphShapes: gl.getUniformLocation(program, 'u_morphShapes'),
            morphSpeed: gl.getUniformLocation(program, 'u_morphSpeed'),
            morphScale: gl.getUniformLocation(program, 'u_morphScale'),
            morphBlend: gl.getUniformLocation(program, 'u_morphBlend'),

            liquidShine: gl.getUniformLocation(program, 'u_liquidShine'),
            liquidFlow: gl.getUniformLocation(program, 'u_liquidFlow'),
            liquidScale: gl.getUniformLocation(program, 'u_liquidScale'),
            liquidRipple: gl.getUniformLocation(program, 'u_liquidRipple'),

            mandelbrotIter: gl.getUniformLocation(program, 'u_mandelbrotIter'),
            mandelbrotZoom: gl.getUniformLocation(program, 'u_mandelbrotZoom'),
            mandelbrotJuliaMix: gl.getUniformLocation(program, 'u_mandelbrotJuliaMix'),
            mandelbrotSpeed: gl.getUniformLocation(program, 'u_mandelbrotSpeed'),

            fireIntensity: gl.getUniformLocation(program, 'u_fireIntensity'),
            fireSpeed: gl.getUniformLocation(program, 'u_fireSpeed'),
            fireTurbulence: gl.getUniformLocation(program, 'u_fireTurbulence'),
            fireHeight: gl.getUniformLocation(program, 'u_fireHeight'),

            auroraBands: gl.getUniformLocation(program, 'u_auroraBands'),
            auroraSpeed: gl.getUniformLocation(program, 'u_auroraSpeed'),
            auroraWave: gl.getUniformLocation(program, 'u_auroraWave'),
            auroraGlow: gl.getUniformLocation(program, 'u_auroraGlow'),

            particleCount: gl.getUniformLocation(program, 'u_particleCount'),
            particleSpeed: gl.getUniformLocation(program, 'u_particleSpeed'),
            particleSize: gl.getUniformLocation(program, 'u_particleSize'),
            particleTrail: gl.getUniformLocation(program, 'u_particleTrail'),
        };
    }
}
